// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.36.1
// source: xas.proto

package v1alpha

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PolicyId uniquely identifies a ScalingPolicy across clusters.
type PolicyId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The cluster this policy belongs to.
	ClusterName string `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	// The namespace of the policy.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The name of the policy.
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyId) Reset() {
	*x = PolicyId{}
	mi := &file_xas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyId) ProtoMessage() {}

func (x *PolicyId) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyId.ProtoReflect.Descriptor instead.
func (*PolicyId) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyId) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *PolicyId) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PolicyId) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// UpdatePolicyRequest is used to create or update a policy definition.
type UpdatePolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The policy definition.
	Policy        *Policy `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePolicyRequest) Reset() {
	*x = UpdatePolicyRequest{}
	mi := &file_xas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolicyRequest) ProtoMessage() {}

func (x *UpdatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePolicyRequest) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

// DeletePolicyRequest identifies a policy to delete.
type DeletePolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the policy.
	Id            *PolicyId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyRequest) Reset() {
	*x = DeletePolicyRequest{}
	mi := &file_xas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyRequest) ProtoMessage() {}

func (x *DeletePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyRequest.ProtoReflect.Descriptor instead.
func (*DeletePolicyRequest) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{2}
}

func (x *DeletePolicyRequest) GetId() *PolicyId {
	if x != nil {
		return x.Id
	}
	return nil
}

// ListPoliciesRequest is used to list policies.
type ListPoliciesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The cluster to list policies for (required).
	ClusterName   string `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_xas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{3}
}

func (x *ListPoliciesRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

// ListPoliciesResponse returns the list of matching policies.
type ListPoliciesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of policies.
	Policies      []*Policy `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesResponse) Reset() {
	*x = ListPoliciesResponse{}
	mi := &file_xas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesResponse) ProtoMessage() {}

func (x *ListPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{4}
}

func (x *ListPoliciesResponse) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

// Policy represents the configuration for autoscaling a specific workload.
type Policy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the policy.
	Id *PolicyId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Reference to the target workload to scale.
	Workload *WorkloadRef `protobuf:"bytes,3,opt,name=workload,proto3" json:"workload,omitempty"`
	// Minimum number of replicas.
	MinReplicas int32 `protobuf:"varint,4,opt,name=min_replicas,json=minReplicas,proto3" json:"min_replicas,omitempty"`
	// Maximum number of replicas.
	MaxReplicas int32 `protobuf:"varint,5,opt,name=max_replicas,json=maxReplicas,proto3" json:"max_replicas,omitempty"`
	// Definitions of metrics to collect and aggregate.
	Metrics []*MetricDefinition `protobuf:"bytes,6,rep,name=metrics,proto3" json:"metrics,omitempty"`
	// Rules for activating/deactivating the workload (Scale to Zero).
	Activation []*RecommenderDefinition `protobuf:"bytes,7,rep,name=activation,proto3" json:"activation,omitempty"`
	// Rules for scaling the workload when active (Horizontal Scaling).
	Scaling []*RecommenderDefinition `protobuf:"bytes,8,rep,name=scaling,proto3" json:"scaling,omitempty"`
	// The label selector used to identify pods (e.g. "app=my-app").
	Selector      string `protobuf:"bytes,9,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_xas_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{5}
}

func (x *Policy) GetId() *PolicyId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Policy) GetWorkload() *WorkloadRef {
	if x != nil {
		return x.Workload
	}
	return nil
}

func (x *Policy) GetMinReplicas() int32 {
	if x != nil {
		return x.MinReplicas
	}
	return 0
}

func (x *Policy) GetMaxReplicas() int32 {
	if x != nil {
		return x.MaxReplicas
	}
	return 0
}

func (x *Policy) GetMetrics() []*MetricDefinition {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Policy) GetActivation() []*RecommenderDefinition {
	if x != nil {
		return x.Activation
	}
	return nil
}

func (x *Policy) GetScaling() []*RecommenderDefinition {
	if x != nil {
		return x.Scaling
	}
	return nil
}

func (x *Policy) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

// WorkloadRef identifies the Kubernetes resource to scale.
type WorkloadRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API Group (e.g., "apps").
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// API Version (e.g., "v1").
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Resource Kind (e.g., "Deployment").
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// Name of the resource.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace of the resource.
	Namespace     string `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadRef) Reset() {
	*x = WorkloadRef{}
	mi := &file_xas_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadRef) ProtoMessage() {}

func (x *WorkloadRef) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadRef.ProtoReflect.Descriptor instead.
func (*WorkloadRef) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{6}
}

func (x *WorkloadRef) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *WorkloadRef) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WorkloadRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WorkloadRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// MetricDefinition defines how to collect and process a metric.
type MetricDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the metric (used as key in ControlMetrics).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The provider class to use (e.g., "kubelet", "prometheus").
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	// Provider-specific parameters (e.g., "type": "cpu").
	Params map[string]string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Label filters to apply to raw samples before processing.
	Filter map[string]string `protobuf:"bytes,5,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// --- Intents ---
	Gauge                *Gauge                `protobuf:"bytes,10,opt,name=gauge,proto3" json:"gauge,omitempty"`
	Rate                 *Rate                 `protobuf:"bytes,11,opt,name=rate,proto3" json:"rate,omitempty"`
	Distribution         *Distribution         `protobuf:"bytes,12,opt,name=distribution,proto3" json:"distribution,omitempty"`
	DecayingDistribution *DecayingDistribution `protobuf:"bytes,13,opt,name=decaying_distribution,json=decayingDistribution,proto3" json:"decaying_distribution,omitempty"`
	// The scope of the metric: "Global" (default) or "Pod".
	Scope         string `protobuf:"bytes,14,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricDefinition) Reset() {
	*x = MetricDefinition{}
	mi := &file_xas_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricDefinition) ProtoMessage() {}

func (x *MetricDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricDefinition.ProtoReflect.Descriptor instead.
func (*MetricDefinition) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{7}
}

func (x *MetricDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricDefinition) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *MetricDefinition) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *MetricDefinition) GetFilter() map[string]string {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *MetricDefinition) GetGauge() *Gauge {
	if x != nil {
		return x.Gauge
	}
	return nil
}

func (x *MetricDefinition) GetRate() *Rate {
	if x != nil {
		return x.Rate
	}
	return nil
}

func (x *MetricDefinition) GetDistribution() *Distribution {
	if x != nil {
		return x.Distribution
	}
	return nil
}

func (x *MetricDefinition) GetDecayingDistribution() *DecayingDistribution {
	if x != nil {
		return x.DecayingDistribution
	}
	return nil
}

func (x *MetricDefinition) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type Gauge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aggregation method: "Avg", "Sum", "Max", "Min".
	Aggregation   string `protobuf:"bytes,1,opt,name=aggregation,proto3" json:"aggregation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gauge) Reset() {
	*x = Gauge{}
	mi := &file_xas_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gauge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gauge) ProtoMessage() {}

func (x *Gauge) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gauge.ProtoReflect.Descriptor instead.
func (*Gauge) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{8}
}

func (x *Gauge) GetAggregation() string {
	if x != nil {
		return x.Aggregation
	}
	return ""
}

type Rate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The temporal period for rate calculation (e.g. "1m").
	Window string `protobuf:"bytes,1,opt,name=window,proto3" json:"window,omitempty"`
	// Aggregation method: "Avg", "Sum", "Max", "Min".
	Aggregation   string `protobuf:"bytes,2,opt,name=aggregation,proto3" json:"aggregation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rate) Reset() {
	*x = Rate{}
	mi := &file_xas_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rate) ProtoMessage() {}

func (x *Rate) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rate.ProtoReflect.Descriptor instead.
func (*Rate) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{9}
}

func (x *Rate) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

func (x *Rate) GetAggregation() string {
	if x != nil {
		return x.Aggregation
	}
	return ""
}

type Distribution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The percentile to extract (e.g. "p99").
	Percentile string `protobuf:"bytes,1,opt,name=percentile,proto3" json:"percentile,omitempty"`
	// Aggregation method: "Avg", "Sum", "Max", "Min".
	Aggregation   string `protobuf:"bytes,2,opt,name=aggregation,proto3" json:"aggregation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Distribution) Reset() {
	*x = Distribution{}
	mi := &file_xas_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Distribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distribution) ProtoMessage() {}

func (x *Distribution) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Distribution.ProtoReflect.Descriptor instead.
func (*Distribution) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{10}
}

func (x *Distribution) GetPercentile() string {
	if x != nil {
		return x.Percentile
	}
	return ""
}

func (x *Distribution) GetAggregation() string {
	if x != nil {
		return x.Aggregation
	}
	return ""
}

type DecayingDistribution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Half-life duration string (e.g. "24h").
	HalfLife string `protobuf:"bytes,1,opt,name=half_life,json=halfLife,proto3" json:"half_life,omitempty"`
	// Bucket size string (e.g. "0.1").
	BucketSize string `protobuf:"bytes,2,opt,name=bucket_size,json=bucketSize,proto3" json:"bucket_size,omitempty"`
	// The percentile to extract (e.g. "p100").
	Percentile string `protobuf:"bytes,3,opt,name=percentile,proto3" json:"percentile,omitempty"`
	// If set, treat input as Counter and calculate rate over this window before sampling.
	Rate          string `protobuf:"bytes,4,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecayingDistribution) Reset() {
	*x = DecayingDistribution{}
	mi := &file_xas_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecayingDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecayingDistribution) ProtoMessage() {}

func (x *DecayingDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecayingDistribution.ProtoReflect.Descriptor instead.
func (*DecayingDistribution) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{11}
}

func (x *DecayingDistribution) GetHalfLife() string {
	if x != nil {
		return x.HalfLife
	}
	return ""
}

func (x *DecayingDistribution) GetBucketSize() string {
	if x != nil {
		return x.BucketSize
	}
	return ""
}

func (x *DecayingDistribution) GetPercentile() string {
	if x != nil {
		return x.Percentile
	}
	return ""
}

func (x *DecayingDistribution) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

// RecommenderDefinition configures a specific scaling algorithm.
type RecommenderDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The class of recommender to use (e.g., "linear-fast").
	Recommender string `protobuf:"bytes,1,opt,name=recommender,proto3" json:"recommender,omitempty"`
	// Unique name for this recommender instance.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Mode of operation: "Active" (default) or "DryRun".
	Mode string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	// Algorithm-specific parameters.
	Params map[string]string `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The type of recommender algorithm (e.g. "Linear", "Threshold").
	Type          string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommenderDefinition) Reset() {
	*x = RecommenderDefinition{}
	mi := &file_xas_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommenderDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommenderDefinition) ProtoMessage() {}

func (x *RecommenderDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommenderDefinition.ProtoReflect.Descriptor instead.
func (*RecommenderDefinition) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{12}
}

func (x *RecommenderDefinition) GetRecommender() string {
	if x != nil {
		return x.Recommender
	}
	return ""
}

func (x *RecommenderDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecommenderDefinition) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RecommenderDefinition) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *RecommenderDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// UpdateWorkloadRequest synchronizes the Control Plane's view of the workload.
type UpdateWorkloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The policy this workload belongs to.
	Id *PolicyId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The current state of the workload (pods).
	Workload      *Workload `protobuf:"bytes,2,opt,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkloadRequest) Reset() {
	*x = UpdateWorkloadRequest{}
	mi := &file_xas_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkloadRequest) ProtoMessage() {}

func (x *UpdateWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkloadRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateWorkloadRequest) GetId() *PolicyId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdateWorkloadRequest) GetWorkload() *Workload {
	if x != nil {
		return x.Workload
	}
	return nil
}

// Workload represents the set of pods governed by a policy.
type Workload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of known pods.
	Pods          []*PodState `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workload) Reset() {
	*x = Workload{}
	mi := &file_xas_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{14}
}

func (x *Workload) GetPods() []*PodState {
	if x != nil {
		return x.Pods
	}
	return nil
}

// PodState represents a single pod instance.
type PodState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the pod.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The node where the pod is running.
	NodeName string `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// Whether the pod is ready to serve traffic.
	IsReady       bool `protobuf:"varint,3,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodState) Reset() {
	*x = PodState{}
	mi := &file_xas_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodState) ProtoMessage() {}

func (x *PodState) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodState.ProtoReflect.Descriptor instead.
func (*PodState) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{15}
}

func (x *PodState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodState) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *PodState) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

// GetControlMetricsRequest retrieves aggregated metrics for a policy.
type GetControlMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The policy to fetch metrics for.
	Id            *PolicyId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetControlMetricsRequest) Reset() {
	*x = GetControlMetricsRequest{}
	mi := &file_xas_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetControlMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetControlMetricsRequest) ProtoMessage() {}

func (x *GetControlMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetControlMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetControlMetricsRequest) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{16}
}

func (x *GetControlMetricsRequest) GetId() *PolicyId {
	if x != nil {
		return x.Id
	}
	return nil
}

// PodMetrics contains metrics for a specific pod.
type PodMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of MetricName -> Value.
	Values        map[string]float64 `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodMetrics) Reset() {
	*x = PodMetrics{}
	mi := &file_xas_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodMetrics) ProtoMessage() {}

func (x *PodMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodMetrics.ProtoReflect.Descriptor instead.
func (*PodMetrics) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{17}
}

func (x *PodMetrics) GetValues() map[string]float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

// ControlMetrics contains the aggregated values calculated by the Control Plane.
type ControlMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of MetricName -> Aggregated Value.
	Values map[string]float64 `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	// Timestamp of the calculation (Unix seconds).
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The number of ready replicas.
	ReadyReplicas int32 `protobuf:"varint,3,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	// Map of PodName -> PodMetrics (for Pod-scoped metrics).
	PodMetrics    map[string]*PodMetrics `protobuf:"bytes,4,rep,name=pod_metrics,json=podMetrics,proto3" json:"pod_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMetrics) Reset() {
	*x = ControlMetrics{}
	mi := &file_xas_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMetrics) ProtoMessage() {}

func (x *ControlMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMetrics.ProtoReflect.Descriptor instead.
func (*ControlMetrics) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{18}
}

func (x *ControlMetrics) GetValues() map[string]float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ControlMetrics) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ControlMetrics) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *ControlMetrics) GetPodMetrics() map[string]*PodMetrics {
	if x != nil {
		return x.PodMetrics
	}
	return nil
}

// UpdateRecommenderStateRequest updates the status (decision) of a recommender.
type UpdateRecommenderStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The policy ID.
	Id *PolicyId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the recommender to update.
	RecommenderName string `protobuf:"bytes,2,opt,name=recommender_name,json=recommenderName,proto3" json:"recommender_name,omitempty"`
	// The new status/decision (Vote).
	Vote          *RecommenderVote `protobuf:"bytes,3,opt,name=vote,proto3" json:"vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecommenderStateRequest) Reset() {
	*x = UpdateRecommenderStateRequest{}
	mi := &file_xas_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecommenderStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecommenderStateRequest) ProtoMessage() {}

func (x *UpdateRecommenderStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecommenderStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecommenderStateRequest) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateRecommenderStateRequest) GetId() *PolicyId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdateRecommenderStateRequest) GetRecommenderName() string {
	if x != nil {
		return x.RecommenderName
	}
	return ""
}

func (x *UpdateRecommenderStateRequest) GetVote() *RecommenderVote {
	if x != nil {
		return x.Vote
	}
	return nil
}

// ResourceRecommendation defines CPU and Memory requests/limits for a workload.
type ResourceRecommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      map[string]string      `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Limits        map[string]string      `protobuf:"bytes,2,rep,name=limits,proto3" json:"limits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRecommendation) Reset() {
	*x = ResourceRecommendation{}
	mi := &file_xas_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRecommendation) ProtoMessage() {}

func (x *ResourceRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRecommendation.ProtoReflect.Descriptor instead.
func (*ResourceRecommendation) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{20}
}

func (x *ResourceRecommendation) GetRequests() map[string]string {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ResourceRecommendation) GetLimits() map[string]string {
	if x != nil {
		return x.Limits
	}
	return nil
}

// PodResourceRecommendation defines CPU and Memory requests/limits for a specific pod.
type PodResourceRecommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodName       string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Requests      map[string]string      `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Limits        map[string]string      `protobuf:"bytes,3,rep,name=limits,proto3" json:"limits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodResourceRecommendation) Reset() {
	*x = PodResourceRecommendation{}
	mi := &file_xas_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodResourceRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodResourceRecommendation) ProtoMessage() {}

func (x *PodResourceRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodResourceRecommendation.ProtoReflect.Descriptor instead.
func (*PodResourceRecommendation) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{21}
}

func (x *PodResourceRecommendation) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodResourceRecommendation) GetRequests() map[string]string {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *PodResourceRecommendation) GetLimits() map[string]string {
	if x != nil {
		return x.Limits
	}
	return nil
}

// RecommenderVote represents the input/decision from a recommender.
type RecommenderVote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The desired number of replicas.
	DesiredReplicas int32 `protobuf:"varint,1,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	// If false, this recommender votes to scale to zero (if Activation type).
	IsActive bool `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// Human-readable reason or message.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Workload-level resource recommendation.
	WorkloadResources *ResourceRecommendation `protobuf:"bytes,4,opt,name=workload_resources,json=workloadResources,proto3" json:"workload_resources,omitempty"`
	// Pod-level resource recommendations.
	PodResources  []*PodResourceRecommendation `protobuf:"bytes,5,rep,name=pod_resources,json=podResources,proto3" json:"pod_resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommenderVote) Reset() {
	*x = RecommenderVote{}
	mi := &file_xas_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommenderVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommenderVote) ProtoMessage() {}

func (x *RecommenderVote) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommenderVote.ProtoReflect.Descriptor instead.
func (*RecommenderVote) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{22}
}

func (x *RecommenderVote) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *RecommenderVote) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *RecommenderVote) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RecommenderVote) GetWorkloadResources() *ResourceRecommendation {
	if x != nil {
		return x.WorkloadResources
	}
	return nil
}

func (x *RecommenderVote) GetPodResources() []*PodResourceRecommendation {
	if x != nil {
		return x.PodResources
	}
	return nil
}

// RecommenderState represents the full state of a recommender (Config + Status).
type RecommenderState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the recommender.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Configuration parameters for this recommender (from Policy).
	Config map[string]string `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The current decision/status of this recommender.
	Status        *RecommenderStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommenderState) Reset() {
	*x = RecommenderState{}
	mi := &file_xas_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommenderState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommenderState) ProtoMessage() {}

func (x *RecommenderState) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommenderState.ProtoReflect.Descriptor instead.
func (*RecommenderState) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{23}
}

func (x *RecommenderState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecommenderState) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RecommenderState) GetStatus() *RecommenderStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// RecommenderStatus represents the output/decision of a recommender.
type RecommenderStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The desired number of replicas.
	DesiredReplicas int32 `protobuf:"varint,1,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	// If false, this recommender votes to scale to zero (if Activation type).
	IsActive bool `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// Human-readable reason or message.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Timestamp of the last update.
	LastUpdated *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	// The phase of the recommender: "Scaling" or "Activation".
	Phase string `protobuf:"bytes,5,opt,name=phase,proto3" json:"phase,omitempty"`
	// The mode of the recommender: "Active" or "DryRun".
	Mode string `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	// The name of the recommender.
	Name string `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	// The type of the recommender (e.g. "Linear", "Cron").
	Type string `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	// Workload-level resource recommendation.
	WorkloadResources *ResourceRecommendation `protobuf:"bytes,9,opt,name=workload_resources,json=workloadResources,proto3" json:"workload_resources,omitempty"`
	// Pod-level resource recommendations.
	PodResources  []*PodResourceRecommendation `protobuf:"bytes,10,rep,name=pod_resources,json=podResources,proto3" json:"pod_resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommenderStatus) Reset() {
	*x = RecommenderStatus{}
	mi := &file_xas_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommenderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommenderStatus) ProtoMessage() {}

func (x *RecommenderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommenderStatus.ProtoReflect.Descriptor instead.
func (*RecommenderStatus) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{24}
}

func (x *RecommenderStatus) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *RecommenderStatus) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *RecommenderStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RecommenderStatus) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *RecommenderStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *RecommenderStatus) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RecommenderStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecommenderStatus) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RecommenderStatus) GetWorkloadResources() *ResourceRecommendation {
	if x != nil {
		return x.WorkloadResources
	}
	return nil
}

func (x *RecommenderStatus) GetPodResources() []*PodResourceRecommendation {
	if x != nil {
		return x.PodResources
	}
	return nil
}

// GetRecommendationRequest retrieves the final recommendation for a policy.
type GetRecommendationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The policy ID.
	Id            *PolicyId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationRequest) Reset() {
	*x = GetRecommendationRequest{}
	mi := &file_xas_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationRequest) ProtoMessage() {}

func (x *GetRecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationRequest) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{25}
}

func (x *GetRecommendationRequest) GetId() *PolicyId {
	if x != nil {
		return x.Id
	}
	return nil
}

// GetRecommendationResponse wraps the recommendation.
// If recommendation is not set, it means no decision is available yet.
type GetRecommendationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Recommendation *Recommendation        `protobuf:"bytes,1,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	// Status of the input metrics used for the decision.
	MetricStatuses []*MetricStatus `protobuf:"bytes,2,rep,name=metric_statuses,json=metricStatuses,proto3" json:"metric_statuses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRecommendationResponse) Reset() {
	*x = GetRecommendationResponse{}
	mi := &file_xas_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationResponse) ProtoMessage() {}

func (x *GetRecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationResponse) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{26}
}

func (x *GetRecommendationResponse) GetRecommendation() *Recommendation {
	if x != nil {
		return x.Recommendation
	}
	return nil
}

func (x *GetRecommendationResponse) GetMetricStatuses() []*MetricStatus {
	if x != nil {
		return x.MetricStatuses
	}
	return nil
}

// Recommendation is the final arbitrated decision from the Control Plane.
type Recommendation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The calculated target replica count.
	TargetReplicas int32 `protobuf:"varint,1,opt,name=target_replicas,json=targetReplicas,proto3" json:"target_replicas,omitempty"`
	// Explains the decision by listing the status of all recommenders.
	Explanation   []*RecommenderStatus `protobuf:"bytes,2,rep,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	mi := &file_xas_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{27}
}

func (x *Recommendation) GetTargetReplicas() int32 {
	if x != nil {
		return x.TargetReplicas
	}
	return 0
}

func (x *Recommendation) GetExplanation() []*RecommenderStatus {
	if x != nil {
		return x.Explanation
	}
	return nil
}

// MetricStatus represents the state of a single input metric.
type MetricStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the metric.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The aggregated value.
	Value float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	// Timestamp of the value (Unix seconds).
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Error message if data is missing or invalid.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricStatus) Reset() {
	*x = MetricStatus{}
	mi := &file_xas_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricStatus) ProtoMessage() {}

func (x *MetricStatus) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricStatus.ProtoReflect.Descriptor instead.
func (*MetricStatus) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{28}
}

func (x *MetricStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricStatus) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// IngestMetricsRequest pushes a batch of raw metrics to the Control Plane.
type IngestMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The cluster name where metrics originated.
	ClusterName string `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	// Timestamp of the ingestion (Unix seconds).
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Group metrics by policy.
	Policies      []*PolicyBatch `protobuf:"bytes,3,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestMetricsRequest) Reset() {
	*x = IngestMetricsRequest{}
	mi := &file_xas_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestMetricsRequest) ProtoMessage() {}

func (x *IngestMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestMetricsRequest.ProtoReflect.Descriptor instead.
func (*IngestMetricsRequest) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{29}
}

func (x *IngestMetricsRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *IngestMetricsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *IngestMetricsRequest) GetPolicies() []*PolicyBatch {
	if x != nil {
		return x.Policies
	}
	return nil
}

// PolicyBatch groups metrics for a specific policy.
type PolicyBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace of the policy.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The name of the policy.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Batches of metrics, usually grouped by Entity (Pod).
	Batches       []*MetricBatch `protobuf:"bytes,3,rep,name=batches,proto3" json:"batches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyBatch) Reset() {
	*x = PolicyBatch{}
	mi := &file_xas_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyBatch) ProtoMessage() {}

func (x *PolicyBatch) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyBatch.ProtoReflect.Descriptor instead.
func (*PolicyBatch) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{30}
}

func (x *PolicyBatch) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PolicyBatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PolicyBatch) GetBatches() []*MetricBatch {
	if x != nil {
		return x.Batches
	}
	return nil
}

// MetricBatch contains metrics for a specific entity.
type MetricBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies the source entity (e.g. Pod Name).
	// Empty string means the metric applies to the Policy as a whole (Global).
	EntityKey string `protobuf:"bytes,1,opt,name=entity_key,json=entityKey,proto3" json:"entity_key,omitempty"`
	// The list of metric samples.
	Samples       []*MetricSample `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricBatch) Reset() {
	*x = MetricBatch{}
	mi := &file_xas_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricBatch) ProtoMessage() {}

func (x *MetricBatch) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricBatch.ProtoReflect.Descriptor instead.
func (*MetricBatch) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{31}
}

func (x *MetricBatch) GetEntityKey() string {
	if x != nil {
		return x.EntityKey
	}
	return ""
}

func (x *MetricBatch) GetSamples() []*MetricSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

// MetricSample represents a single data point.
type MetricSample struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the metric.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Labels associated with the sample.
	Labels map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The scalar value of the sample.
	Value float64 `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	// Timestamp of the sample (Unix seconds).
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Histogram buckets (Le -> Count).
	HistogramBuckets map[string]uint64 `protobuf:"bytes,5,rep,name=histogram_buckets,json=histogramBuckets,proto3" json:"histogram_buckets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Sum of all observations in the histogram.
	HistogramSum float64 `protobuf:"fixed64,6,opt,name=histogram_sum,json=histogramSum,proto3" json:"histogram_sum,omitempty"`
	// Total count of observations in the histogram.
	HistogramCount uint64 `protobuf:"varint,7,opt,name=histogram_count,json=histogramCount,proto3" json:"histogram_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetricSample) Reset() {
	*x = MetricSample{}
	mi := &file_xas_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSample) ProtoMessage() {}

func (x *MetricSample) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSample.ProtoReflect.Descriptor instead.
func (*MetricSample) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{32}
}

func (x *MetricSample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricSample) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetricSample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricSample) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricSample) GetHistogramBuckets() map[string]uint64 {
	if x != nil {
		return x.HistogramBuckets
	}
	return nil
}

func (x *MetricSample) GetHistogramSum() float64 {
	if x != nil {
		return x.HistogramSum
	}
	return 0
}

func (x *MetricSample) GetHistogramCount() uint64 {
	if x != nil {
		return x.HistogramCount
	}
	return 0
}

// IngestMetricsResponse acknowledges successful ingestion.
type IngestMetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether ingestion was successful.
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestMetricsResponse) Reset() {
	*x = IngestMetricsResponse{}
	mi := &file_xas_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestMetricsResponse) ProtoMessage() {}

func (x *IngestMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xas_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestMetricsResponse.ProtoReflect.Descriptor instead.
func (*IngestMetricsResponse) Descriptor() ([]byte, []int) {
	return file_xas_proto_rawDescGZIP(), []int{33}
}

func (x *IngestMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_xas_proto protoreflect.FileDescriptor

const file_xas_proto_rawDesc = "" +
	"\n" +
	"\txas.proto\x12\vxas.v1alpha\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"_\n" +
	"\bPolicyId\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"B\n" +
	"\x13UpdatePolicyRequest\x12+\n" +
	"\x06policy\x18\x01 \x01(\v2\x13.xas.v1alpha.PolicyR\x06policy\"<\n" +
	"\x13DeletePolicyRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\v2\x15.xas.v1alpha.PolicyIdR\x02id\"8\n" +
	"\x13ListPoliciesRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\"G\n" +
	"\x14ListPoliciesResponse\x12/\n" +
	"\bpolicies\x18\x01 \x03(\v2\x13.xas.v1alpha.PolicyR\bpolicies\"\x82\x03\n" +
	"\x06Policy\x12%\n" +
	"\x02id\x18\x01 \x01(\v2\x15.xas.v1alpha.PolicyIdR\x02id\x124\n" +
	"\bworkload\x18\x03 \x01(\v2\x18.xas.v1alpha.WorkloadRefR\bworkload\x12!\n" +
	"\fmin_replicas\x18\x04 \x01(\x05R\vminReplicas\x12!\n" +
	"\fmax_replicas\x18\x05 \x01(\x05R\vmaxReplicas\x127\n" +
	"\ametrics\x18\x06 \x03(\v2\x1d.xas.v1alpha.MetricDefinitionR\ametrics\x12B\n" +
	"\n" +
	"activation\x18\a \x03(\v2\".xas.v1alpha.RecommenderDefinitionR\n" +
	"activation\x12<\n" +
	"\ascaling\x18\b \x03(\v2\".xas.v1alpha.RecommenderDefinitionR\ascaling\x12\x1a\n" +
	"\bselector\x18\t \x01(\tR\bselector\"\x83\x01\n" +
	"\vWorkloadRef\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\"\xbc\x04\n" +
	"\x10MetricDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12A\n" +
	"\x06params\x18\x03 \x03(\v2).xas.v1alpha.MetricDefinition.ParamsEntryR\x06params\x12A\n" +
	"\x06filter\x18\x05 \x03(\v2).xas.v1alpha.MetricDefinition.FilterEntryR\x06filter\x12(\n" +
	"\x05gauge\x18\n" +
	" \x01(\v2\x12.xas.v1alpha.GaugeR\x05gauge\x12%\n" +
	"\x04rate\x18\v \x01(\v2\x11.xas.v1alpha.RateR\x04rate\x12=\n" +
	"\fdistribution\x18\f \x01(\v2\x19.xas.v1alpha.DistributionR\fdistribution\x12V\n" +
	"\x15decaying_distribution\x18\r \x01(\v2!.xas.v1alpha.DecayingDistributionR\x14decayingDistribution\x12\x14\n" +
	"\x05scope\x18\x0e \x01(\tR\x05scope\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\x05Gauge\x12 \n" +
	"\vaggregation\x18\x01 \x01(\tR\vaggregation\"@\n" +
	"\x04Rate\x12\x16\n" +
	"\x06window\x18\x01 \x01(\tR\x06window\x12 \n" +
	"\vaggregation\x18\x02 \x01(\tR\vaggregation\"P\n" +
	"\fDistribution\x12\x1e\n" +
	"\n" +
	"percentile\x18\x01 \x01(\tR\n" +
	"percentile\x12 \n" +
	"\vaggregation\x18\x02 \x01(\tR\vaggregation\"\x88\x01\n" +
	"\x14DecayingDistribution\x12\x1b\n" +
	"\thalf_life\x18\x01 \x01(\tR\bhalfLife\x12\x1f\n" +
	"\vbucket_size\x18\x02 \x01(\tR\n" +
	"bucketSize\x12\x1e\n" +
	"\n" +
	"percentile\x18\x03 \x01(\tR\n" +
	"percentile\x12\x12\n" +
	"\x04rate\x18\x04 \x01(\tR\x04rate\"\xf8\x01\n" +
	"\x15RecommenderDefinition\x12 \n" +
	"\vrecommender\x18\x01 \x01(\tR\vrecommender\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12F\n" +
	"\x06params\x18\x04 \x03(\v2..xas.v1alpha.RecommenderDefinition.ParamsEntryR\x06params\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\x15UpdateWorkloadRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\v2\x15.xas.v1alpha.PolicyIdR\x02id\x121\n" +
	"\bworkload\x18\x02 \x01(\v2\x15.xas.v1alpha.WorkloadR\bworkload\"5\n" +
	"\bWorkload\x12)\n" +
	"\x04pods\x18\x01 \x03(\v2\x15.xas.v1alpha.PodStateR\x04pods\"V\n" +
	"\bPodState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x19\n" +
	"\bis_ready\x18\x03 \x01(\bR\aisReady\"A\n" +
	"\x18GetControlMetricsRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\v2\x15.xas.v1alpha.PolicyIdR\x02id\"\x84\x01\n" +
	"\n" +
	"PodMetrics\x12;\n" +
	"\x06values\x18\x01 \x03(\v2#.xas.v1alpha.PodMetrics.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xf7\x02\n" +
	"\x0eControlMetrics\x12?\n" +
	"\x06values\x18\x01 \x03(\v2'.xas.v1alpha.ControlMetrics.ValuesEntryR\x06values\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12%\n" +
	"\x0eready_replicas\x18\x03 \x01(\x05R\rreadyReplicas\x12L\n" +
	"\vpod_metrics\x18\x04 \x03(\v2+.xas.v1alpha.ControlMetrics.PodMetricsEntryR\n" +
	"podMetrics\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1aV\n" +
	"\x0fPodMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.xas.v1alpha.PodMetricsR\x05value:\x028\x01\"\xa3\x01\n" +
	"\x1dUpdateRecommenderStateRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\v2\x15.xas.v1alpha.PolicyIdR\x02id\x12)\n" +
	"\x10recommender_name\x18\x02 \x01(\tR\x0frecommenderName\x120\n" +
	"\x04vote\x18\x03 \x01(\v2\x1c.xas.v1alpha.RecommenderVoteR\x04vote\"\xa8\x02\n" +
	"\x16ResourceRecommendation\x12M\n" +
	"\brequests\x18\x01 \x03(\v21.xas.v1alpha.ResourceRecommendation.RequestsEntryR\brequests\x12G\n" +
	"\x06limits\x18\x02 \x03(\v2/.xas.v1alpha.ResourceRecommendation.LimitsEntryR\x06limits\x1a;\n" +
	"\rRequestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLimitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x02\n" +
	"\x19PodResourceRecommendation\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12P\n" +
	"\brequests\x18\x02 \x03(\v24.xas.v1alpha.PodResourceRecommendation.RequestsEntryR\brequests\x12J\n" +
	"\x06limits\x18\x03 \x03(\v22.xas.v1alpha.PodResourceRecommendation.LimitsEntryR\x06limits\x1a;\n" +
	"\rRequestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLimitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x02\n" +
	"\x0fRecommenderVote\x12)\n" +
	"\x10desired_replicas\x18\x01 \x01(\x05R\x0fdesiredReplicas\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12R\n" +
	"\x12workload_resources\x18\x04 \x01(\v2#.xas.v1alpha.ResourceRecommendationR\x11workloadResources\x12K\n" +
	"\rpod_resources\x18\x05 \x03(\v2&.xas.v1alpha.PodResourceRecommendationR\fpodResources\"\xdc\x01\n" +
	"\x10RecommenderState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12A\n" +
	"\x06config\x18\x02 \x03(\v2).xas.v1alpha.RecommenderState.ConfigEntryR\x06config\x126\n" +
	"\x06status\x18\x03 \x01(\v2\x1e.xas.v1alpha.RecommenderStatusR\x06status\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x03\n" +
	"\x11RecommenderStatus\x12)\n" +
	"\x10desired_replicas\x18\x01 \x01(\x05R\x0fdesiredReplicas\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12=\n" +
	"\flast_updated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12\x14\n" +
	"\x05phase\x18\x05 \x01(\tR\x05phase\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12R\n" +
	"\x12workload_resources\x18\t \x01(\v2#.xas.v1alpha.ResourceRecommendationR\x11workloadResources\x12K\n" +
	"\rpod_resources\x18\n" +
	" \x03(\v2&.xas.v1alpha.PodResourceRecommendationR\fpodResources\"A\n" +
	"\x18GetRecommendationRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\v2\x15.xas.v1alpha.PolicyIdR\x02id\"\xa4\x01\n" +
	"\x19GetRecommendationResponse\x12C\n" +
	"\x0erecommendation\x18\x01 \x01(\v2\x1b.xas.v1alpha.RecommendationR\x0erecommendation\x12B\n" +
	"\x0fmetric_statuses\x18\x02 \x03(\v2\x19.xas.v1alpha.MetricStatusR\x0emetricStatuses\"{\n" +
	"\x0eRecommendation\x12'\n" +
	"\x0ftarget_replicas\x18\x01 \x01(\x05R\x0etargetReplicas\x12@\n" +
	"\vexplanation\x18\x02 \x03(\v2\x1e.xas.v1alpha.RecommenderStatusR\vexplanation\"l\n" +
	"\fMetricStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x8d\x01\n" +
	"\x14IngestMetricsRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x124\n" +
	"\bpolicies\x18\x03 \x03(\v2\x18.xas.v1alpha.PolicyBatchR\bpolicies\"s\n" +
	"\vPolicyBatch\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x122\n" +
	"\abatches\x18\x03 \x03(\v2\x18.xas.v1alpha.MetricBatchR\abatches\"a\n" +
	"\vMetricBatch\x12\x1d\n" +
	"\n" +
	"entity_key\x18\x01 \x01(\tR\tentityKey\x123\n" +
	"\asamples\x18\x02 \x03(\v2\x19.xas.v1alpha.MetricSampleR\asamples\"\xc1\x03\n" +
	"\fMetricSample\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12=\n" +
	"\x06labels\x18\x02 \x03(\v2%.xas.v1alpha.MetricSample.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\\\n" +
	"\x11histogram_buckets\x18\x05 \x03(\v2/.xas.v1alpha.MetricSample.HistogramBucketsEntryR\x10histogramBuckets\x12#\n" +
	"\rhistogram_sum\x18\x06 \x01(\x01R\fhistogramSum\x12'\n" +
	"\x0fhistogram_count\x18\a \x01(\x04R\x0ehistogramCount\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n" +
	"\x15HistogramBucketsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"1\n" +
	"\x15IngestMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xbe\x05\n" +
	"\x0fXASControlPlane\x12E\n" +
	"\fUpdatePolicy\x12 .xas.v1alpha.UpdatePolicyRequest\x1a\x13.xas.v1alpha.Policy\x12H\n" +
	"\fDeletePolicy\x12 .xas.v1alpha.DeletePolicyRequest\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\fListPolicies\x12 .xas.v1alpha.ListPoliciesRequest\x1a!.xas.v1alpha.ListPoliciesResponse\x12K\n" +
	"\x0eUpdateWorkload\x12\".xas.v1alpha.UpdateWorkloadRequest\x1a\x15.xas.v1alpha.Workload\x12W\n" +
	"\x11GetControlMetrics\x12%.xas.v1alpha.GetControlMetricsRequest\x1a\x1b.xas.v1alpha.ControlMetrics\x12c\n" +
	"\x16UpdateRecommenderState\x12*.xas.v1alpha.UpdateRecommenderStateRequest\x1a\x1d.xas.v1alpha.RecommenderState\x12b\n" +
	"\x11GetRecommendation\x12%.xas.v1alpha.GetRecommendationRequest\x1a&.xas.v1alpha.GetRecommendationResponse\x12V\n" +
	"\rIngestMetrics\x12!.xas.v1alpha.IngestMetricsRequest\x1a\".xas.v1alpha.IngestMetricsResponseB@Z>github.com/gke-labs/extensible-workload-autoscaler/api/v1alphab\x06proto3"

var (
	file_xas_proto_rawDescOnce sync.Once
	file_xas_proto_rawDescData []byte
)

func file_xas_proto_rawDescGZIP() []byte {
	file_xas_proto_rawDescOnce.Do(func() {
		file_xas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xas_proto_rawDesc), len(file_xas_proto_rawDesc)))
	})
	return file_xas_proto_rawDescData
}

var file_xas_proto_msgTypes = make([]protoimpl.MessageInfo, 47)
var file_xas_proto_goTypes = []any{
	(*PolicyId)(nil),                      // 0: xas.v1alpha.PolicyId
	(*UpdatePolicyRequest)(nil),           // 1: xas.v1alpha.UpdatePolicyRequest
	(*DeletePolicyRequest)(nil),           // 2: xas.v1alpha.DeletePolicyRequest
	(*ListPoliciesRequest)(nil),           // 3: xas.v1alpha.ListPoliciesRequest
	(*ListPoliciesResponse)(nil),          // 4: xas.v1alpha.ListPoliciesResponse
	(*Policy)(nil),                        // 5: xas.v1alpha.Policy
	(*WorkloadRef)(nil),                   // 6: xas.v1alpha.WorkloadRef
	(*MetricDefinition)(nil),              // 7: xas.v1alpha.MetricDefinition
	(*Gauge)(nil),                         // 8: xas.v1alpha.Gauge
	(*Rate)(nil),                          // 9: xas.v1alpha.Rate
	(*Distribution)(nil),                  // 10: xas.v1alpha.Distribution
	(*DecayingDistribution)(nil),          // 11: xas.v1alpha.DecayingDistribution
	(*RecommenderDefinition)(nil),         // 12: xas.v1alpha.RecommenderDefinition
	(*UpdateWorkloadRequest)(nil),         // 13: xas.v1alpha.UpdateWorkloadRequest
	(*Workload)(nil),                      // 14: xas.v1alpha.Workload
	(*PodState)(nil),                      // 15: xas.v1alpha.PodState
	(*GetControlMetricsRequest)(nil),      // 16: xas.v1alpha.GetControlMetricsRequest
	(*PodMetrics)(nil),                    // 17: xas.v1alpha.PodMetrics
	(*ControlMetrics)(nil),                // 18: xas.v1alpha.ControlMetrics
	(*UpdateRecommenderStateRequest)(nil), // 19: xas.v1alpha.UpdateRecommenderStateRequest
	(*ResourceRecommendation)(nil),        // 20: xas.v1alpha.ResourceRecommendation
	(*PodResourceRecommendation)(nil),     // 21: xas.v1alpha.PodResourceRecommendation
	(*RecommenderVote)(nil),               // 22: xas.v1alpha.RecommenderVote
	(*RecommenderState)(nil),              // 23: xas.v1alpha.RecommenderState
	(*RecommenderStatus)(nil),             // 24: xas.v1alpha.RecommenderStatus
	(*GetRecommendationRequest)(nil),      // 25: xas.v1alpha.GetRecommendationRequest
	(*GetRecommendationResponse)(nil),     // 26: xas.v1alpha.GetRecommendationResponse
	(*Recommendation)(nil),                // 27: xas.v1alpha.Recommendation
	(*MetricStatus)(nil),                  // 28: xas.v1alpha.MetricStatus
	(*IngestMetricsRequest)(nil),          // 29: xas.v1alpha.IngestMetricsRequest
	(*PolicyBatch)(nil),                   // 30: xas.v1alpha.PolicyBatch
	(*MetricBatch)(nil),                   // 31: xas.v1alpha.MetricBatch
	(*MetricSample)(nil),                  // 32: xas.v1alpha.MetricSample
	(*IngestMetricsResponse)(nil),         // 33: xas.v1alpha.IngestMetricsResponse
	nil,                                   // 34: xas.v1alpha.MetricDefinition.ParamsEntry
	nil,                                   // 35: xas.v1alpha.MetricDefinition.FilterEntry
	nil,                                   // 36: xas.v1alpha.RecommenderDefinition.ParamsEntry
	nil,                                   // 37: xas.v1alpha.PodMetrics.ValuesEntry
	nil,                                   // 38: xas.v1alpha.ControlMetrics.ValuesEntry
	nil,                                   // 39: xas.v1alpha.ControlMetrics.PodMetricsEntry
	nil,                                   // 40: xas.v1alpha.ResourceRecommendation.RequestsEntry
	nil,                                   // 41: xas.v1alpha.ResourceRecommendation.LimitsEntry
	nil,                                   // 42: xas.v1alpha.PodResourceRecommendation.RequestsEntry
	nil,                                   // 43: xas.v1alpha.PodResourceRecommendation.LimitsEntry
	nil,                                   // 44: xas.v1alpha.RecommenderState.ConfigEntry
	nil,                                   // 45: xas.v1alpha.MetricSample.LabelsEntry
	nil,                                   // 46: xas.v1alpha.MetricSample.HistogramBucketsEntry
	(*timestamppb.Timestamp)(nil),         // 47: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 48: google.protobuf.Empty
}
var file_xas_proto_depIdxs = []int32{
	5,  // 0: xas.v1alpha.UpdatePolicyRequest.policy:type_name -> xas.v1alpha.Policy
	0,  // 1: xas.v1alpha.DeletePolicyRequest.id:type_name -> xas.v1alpha.PolicyId
	5,  // 2: xas.v1alpha.ListPoliciesResponse.policies:type_name -> xas.v1alpha.Policy
	0,  // 3: xas.v1alpha.Policy.id:type_name -> xas.v1alpha.PolicyId
	6,  // 4: xas.v1alpha.Policy.workload:type_name -> xas.v1alpha.WorkloadRef
	7,  // 5: xas.v1alpha.Policy.metrics:type_name -> xas.v1alpha.MetricDefinition
	12, // 6: xas.v1alpha.Policy.activation:type_name -> xas.v1alpha.RecommenderDefinition
	12, // 7: xas.v1alpha.Policy.scaling:type_name -> xas.v1alpha.RecommenderDefinition
	34, // 8: xas.v1alpha.MetricDefinition.params:type_name -> xas.v1alpha.MetricDefinition.ParamsEntry
	35, // 9: xas.v1alpha.MetricDefinition.filter:type_name -> xas.v1alpha.MetricDefinition.FilterEntry
	8,  // 10: xas.v1alpha.MetricDefinition.gauge:type_name -> xas.v1alpha.Gauge
	9,  // 11: xas.v1alpha.MetricDefinition.rate:type_name -> xas.v1alpha.Rate
	10, // 12: xas.v1alpha.MetricDefinition.distribution:type_name -> xas.v1alpha.Distribution
	11, // 13: xas.v1alpha.MetricDefinition.decaying_distribution:type_name -> xas.v1alpha.DecayingDistribution
	36, // 14: xas.v1alpha.RecommenderDefinition.params:type_name -> xas.v1alpha.RecommenderDefinition.ParamsEntry
	0,  // 15: xas.v1alpha.UpdateWorkloadRequest.id:type_name -> xas.v1alpha.PolicyId
	14, // 16: xas.v1alpha.UpdateWorkloadRequest.workload:type_name -> xas.v1alpha.Workload
	15, // 17: xas.v1alpha.Workload.pods:type_name -> xas.v1alpha.PodState
	0,  // 18: xas.v1alpha.GetControlMetricsRequest.id:type_name -> xas.v1alpha.PolicyId
	37, // 19: xas.v1alpha.PodMetrics.values:type_name -> xas.v1alpha.PodMetrics.ValuesEntry
	38, // 20: xas.v1alpha.ControlMetrics.values:type_name -> xas.v1alpha.ControlMetrics.ValuesEntry
	39, // 21: xas.v1alpha.ControlMetrics.pod_metrics:type_name -> xas.v1alpha.ControlMetrics.PodMetricsEntry
	0,  // 22: xas.v1alpha.UpdateRecommenderStateRequest.id:type_name -> xas.v1alpha.PolicyId
	22, // 23: xas.v1alpha.UpdateRecommenderStateRequest.vote:type_name -> xas.v1alpha.RecommenderVote
	40, // 24: xas.v1alpha.ResourceRecommendation.requests:type_name -> xas.v1alpha.ResourceRecommendation.RequestsEntry
	41, // 25: xas.v1alpha.ResourceRecommendation.limits:type_name -> xas.v1alpha.ResourceRecommendation.LimitsEntry
	42, // 26: xas.v1alpha.PodResourceRecommendation.requests:type_name -> xas.v1alpha.PodResourceRecommendation.RequestsEntry
	43, // 27: xas.v1alpha.PodResourceRecommendation.limits:type_name -> xas.v1alpha.PodResourceRecommendation.LimitsEntry
	20, // 28: xas.v1alpha.RecommenderVote.workload_resources:type_name -> xas.v1alpha.ResourceRecommendation
	21, // 29: xas.v1alpha.RecommenderVote.pod_resources:type_name -> xas.v1alpha.PodResourceRecommendation
	44, // 30: xas.v1alpha.RecommenderState.config:type_name -> xas.v1alpha.RecommenderState.ConfigEntry
	24, // 31: xas.v1alpha.RecommenderState.status:type_name -> xas.v1alpha.RecommenderStatus
	47, // 32: xas.v1alpha.RecommenderStatus.last_updated:type_name -> google.protobuf.Timestamp
	20, // 33: xas.v1alpha.RecommenderStatus.workload_resources:type_name -> xas.v1alpha.ResourceRecommendation
	21, // 34: xas.v1alpha.RecommenderStatus.pod_resources:type_name -> xas.v1alpha.PodResourceRecommendation
	0,  // 35: xas.v1alpha.GetRecommendationRequest.id:type_name -> xas.v1alpha.PolicyId
	27, // 36: xas.v1alpha.GetRecommendationResponse.recommendation:type_name -> xas.v1alpha.Recommendation
	28, // 37: xas.v1alpha.GetRecommendationResponse.metric_statuses:type_name -> xas.v1alpha.MetricStatus
	24, // 38: xas.v1alpha.Recommendation.explanation:type_name -> xas.v1alpha.RecommenderStatus
	30, // 39: xas.v1alpha.IngestMetricsRequest.policies:type_name -> xas.v1alpha.PolicyBatch
	31, // 40: xas.v1alpha.PolicyBatch.batches:type_name -> xas.v1alpha.MetricBatch
	32, // 41: xas.v1alpha.MetricBatch.samples:type_name -> xas.v1alpha.MetricSample
	45, // 42: xas.v1alpha.MetricSample.labels:type_name -> xas.v1alpha.MetricSample.LabelsEntry
	46, // 43: xas.v1alpha.MetricSample.histogram_buckets:type_name -> xas.v1alpha.MetricSample.HistogramBucketsEntry
	17, // 44: xas.v1alpha.ControlMetrics.PodMetricsEntry.value:type_name -> xas.v1alpha.PodMetrics
	1,  // 45: xas.v1alpha.XASControlPlane.UpdatePolicy:input_type -> xas.v1alpha.UpdatePolicyRequest
	2,  // 46: xas.v1alpha.XASControlPlane.DeletePolicy:input_type -> xas.v1alpha.DeletePolicyRequest
	3,  // 47: xas.v1alpha.XASControlPlane.ListPolicies:input_type -> xas.v1alpha.ListPoliciesRequest
	13, // 48: xas.v1alpha.XASControlPlane.UpdateWorkload:input_type -> xas.v1alpha.UpdateWorkloadRequest
	16, // 49: xas.v1alpha.XASControlPlane.GetControlMetrics:input_type -> xas.v1alpha.GetControlMetricsRequest
	19, // 50: xas.v1alpha.XASControlPlane.UpdateRecommenderState:input_type -> xas.v1alpha.UpdateRecommenderStateRequest
	25, // 51: xas.v1alpha.XASControlPlane.GetRecommendation:input_type -> xas.v1alpha.GetRecommendationRequest
	29, // 52: xas.v1alpha.XASControlPlane.IngestMetrics:input_type -> xas.v1alpha.IngestMetricsRequest
	5,  // 53: xas.v1alpha.XASControlPlane.UpdatePolicy:output_type -> xas.v1alpha.Policy
	48, // 54: xas.v1alpha.XASControlPlane.DeletePolicy:output_type -> google.protobuf.Empty
	4,  // 55: xas.v1alpha.XASControlPlane.ListPolicies:output_type -> xas.v1alpha.ListPoliciesResponse
	14, // 56: xas.v1alpha.XASControlPlane.UpdateWorkload:output_type -> xas.v1alpha.Workload
	18, // 57: xas.v1alpha.XASControlPlane.GetControlMetrics:output_type -> xas.v1alpha.ControlMetrics
	23, // 58: xas.v1alpha.XASControlPlane.UpdateRecommenderState:output_type -> xas.v1alpha.RecommenderState
	26, // 59: xas.v1alpha.XASControlPlane.GetRecommendation:output_type -> xas.v1alpha.GetRecommendationResponse
	33, // 60: xas.v1alpha.XASControlPlane.IngestMetrics:output_type -> xas.v1alpha.IngestMetricsResponse
	53, // [53:61] is the sub-list for method output_type
	45, // [45:53] is the sub-list for method input_type
	45, // [45:45] is the sub-list for extension type_name
	45, // [45:45] is the sub-list for extension extendee
	0,  // [0:45] is the sub-list for field type_name
}

func init() { file_xas_proto_init() }
func file_xas_proto_init() {
	if File_xas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xas_proto_rawDesc), len(file_xas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   47,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xas_proto_goTypes,
		DependencyIndexes: file_xas_proto_depIdxs,
		MessageInfos:      file_xas_proto_msgTypes,
	}.Build()
	File_xas_proto = out.File
	file_xas_proto_goTypes = nil
	file_xas_proto_depIdxs = nil
}
