// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.36.1
// source: xas.proto

package v1alpha

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	XASControlPlane_UpdatePolicy_FullMethodName           = "/xas.v1alpha.XASControlPlane/UpdatePolicy"
	XASControlPlane_DeletePolicy_FullMethodName           = "/xas.v1alpha.XASControlPlane/DeletePolicy"
	XASControlPlane_ListPolicies_FullMethodName           = "/xas.v1alpha.XASControlPlane/ListPolicies"
	XASControlPlane_UpdateWorkload_FullMethodName         = "/xas.v1alpha.XASControlPlane/UpdateWorkload"
	XASControlPlane_GetControlMetrics_FullMethodName      = "/xas.v1alpha.XASControlPlane/GetControlMetrics"
	XASControlPlane_UpdateRecommenderState_FullMethodName = "/xas.v1alpha.XASControlPlane/UpdateRecommenderState"
	XASControlPlane_GetRecommendation_FullMethodName      = "/xas.v1alpha.XASControlPlane/GetRecommendation"
	XASControlPlane_IngestMetrics_FullMethodName          = "/xas.v1alpha.XASControlPlane/IngestMetrics"
)

// XASControlPlaneClient is the client API for XASControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// XASControlPlane defines the gRPC interface for the Control Plane (Server).
// It acts as the central state manager for autoscaling policies, workload state,
// metric ingestion, and decision making.
type XASControlPlaneClient interface {
	// --- Policy Management ---
	// Create or Update a ScalingPolicy. This is an idempotent "Upsert".
	UpdatePolicy(ctx context.Context, in *UpdatePolicyRequest, opts ...grpc.CallOption) (*Policy, error)
	// Delete a ScalingPolicy.
	DeletePolicy(ctx context.Context, in *DeletePolicyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List all known policies, optionally filtered by cluster.
	ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error)
	// --- Workload Management (Controller -> Control Plane) ---
	// Update the Control Plane's view of the workload (Pods) for a specific policy.
	// This is a full replacement of the pod list.
	// TODO(): This method should probably just return an empty response (google.protobuf.Empty).
	UpdateWorkload(ctx context.Context, in *UpdateWorkloadRequest, opts ...grpc.CallOption) (*Workload, error)
	// --- Control Metrics (Recommender -> Control Plane) ---
	// Read the current aggregated metric values ("Control Metrics") for a policy.
	// Recommenders use this to make scaling decisions.
	GetControlMetrics(ctx context.Context, in *GetControlMetricsRequest, opts ...grpc.CallOption) (*ControlMetrics, error)
	// --- Recommender State (Plugin -> Control Plane) ---
	// Update Status (Decision) for a specific recommender.
	// Recommenders push their calculated vote here.
	UpdateRecommenderState(ctx context.Context, in *UpdateRecommenderStateRequest, opts ...grpc.CallOption) (*RecommenderState, error)
	// --- Recommendation (Controller -> Control Plane) ---
	// Retrieve the final arbitrated recommendation for a policy.
	// The Controller uses this to scale the target workload.
	GetRecommendation(ctx context.Context, in *GetRecommendationRequest, opts ...grpc.CallOption) (*GetRecommendationResponse, error)
	// --- Ingestion (Agent -> Control Plane) ---
	// Push raw metric samples from an Agent (Node).
	IngestMetrics(ctx context.Context, in *IngestMetricsRequest, opts ...grpc.CallOption) (*IngestMetricsResponse, error)
}

type xASControlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewXASControlPlaneClient(cc grpc.ClientConnInterface) XASControlPlaneClient {
	return &xASControlPlaneClient{cc}
}

func (c *xASControlPlaneClient) UpdatePolicy(ctx context.Context, in *UpdatePolicyRequest, opts ...grpc.CallOption) (*Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Policy)
	err := c.cc.Invoke(ctx, XASControlPlane_UpdatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xASControlPlaneClient) DeletePolicy(ctx context.Context, in *DeletePolicyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, XASControlPlane_DeletePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xASControlPlaneClient) ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoliciesResponse)
	err := c.cc.Invoke(ctx, XASControlPlane_ListPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xASControlPlaneClient) UpdateWorkload(ctx context.Context, in *UpdateWorkloadRequest, opts ...grpc.CallOption) (*Workload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workload)
	err := c.cc.Invoke(ctx, XASControlPlane_UpdateWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xASControlPlaneClient) GetControlMetrics(ctx context.Context, in *GetControlMetricsRequest, opts ...grpc.CallOption) (*ControlMetrics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlMetrics)
	err := c.cc.Invoke(ctx, XASControlPlane_GetControlMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xASControlPlaneClient) UpdateRecommenderState(ctx context.Context, in *UpdateRecommenderStateRequest, opts ...grpc.CallOption) (*RecommenderState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommenderState)
	err := c.cc.Invoke(ctx, XASControlPlane_UpdateRecommenderState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xASControlPlaneClient) GetRecommendation(ctx context.Context, in *GetRecommendationRequest, opts ...grpc.CallOption) (*GetRecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecommendationResponse)
	err := c.cc.Invoke(ctx, XASControlPlane_GetRecommendation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xASControlPlaneClient) IngestMetrics(ctx context.Context, in *IngestMetricsRequest, opts ...grpc.CallOption) (*IngestMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestMetricsResponse)
	err := c.cc.Invoke(ctx, XASControlPlane_IngestMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XASControlPlaneServer is the server API for XASControlPlane service.
// All implementations must embed UnimplementedXASControlPlaneServer
// for forward compatibility.
//
// XASControlPlane defines the gRPC interface for the Control Plane (Server).
// It acts as the central state manager for autoscaling policies, workload state,
// metric ingestion, and decision making.
type XASControlPlaneServer interface {
	// --- Policy Management ---
	// Create or Update a ScalingPolicy. This is an idempotent "Upsert".
	UpdatePolicy(context.Context, *UpdatePolicyRequest) (*Policy, error)
	// Delete a ScalingPolicy.
	DeletePolicy(context.Context, *DeletePolicyRequest) (*emptypb.Empty, error)
	// List all known policies, optionally filtered by cluster.
	ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error)
	// --- Workload Management (Controller -> Control Plane) ---
	// Update the Control Plane's view of the workload (Pods) for a specific policy.
	// This is a full replacement of the pod list.
	// TODO(): This method should probably just return an empty response (google.protobuf.Empty).
	UpdateWorkload(context.Context, *UpdateWorkloadRequest) (*Workload, error)
	// --- Control Metrics (Recommender -> Control Plane) ---
	// Read the current aggregated metric values ("Control Metrics") for a policy.
	// Recommenders use this to make scaling decisions.
	GetControlMetrics(context.Context, *GetControlMetricsRequest) (*ControlMetrics, error)
	// --- Recommender State (Plugin -> Control Plane) ---
	// Update Status (Decision) for a specific recommender.
	// Recommenders push their calculated vote here.
	UpdateRecommenderState(context.Context, *UpdateRecommenderStateRequest) (*RecommenderState, error)
	// --- Recommendation (Controller -> Control Plane) ---
	// Retrieve the final arbitrated recommendation for a policy.
	// The Controller uses this to scale the target workload.
	GetRecommendation(context.Context, *GetRecommendationRequest) (*GetRecommendationResponse, error)
	// --- Ingestion (Agent -> Control Plane) ---
	// Push raw metric samples from an Agent (Node).
	IngestMetrics(context.Context, *IngestMetricsRequest) (*IngestMetricsResponse, error)
	mustEmbedUnimplementedXASControlPlaneServer()
}

// UnimplementedXASControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedXASControlPlaneServer struct{}

func (UnimplementedXASControlPlaneServer) UpdatePolicy(context.Context, *UpdatePolicyRequest) (*Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePolicy not implemented")
}
func (UnimplementedXASControlPlaneServer) DeletePolicy(context.Context, *DeletePolicyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePolicy not implemented")
}
func (UnimplementedXASControlPlaneServer) ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPolicies not implemented")
}
func (UnimplementedXASControlPlaneServer) UpdateWorkload(context.Context, *UpdateWorkloadRequest) (*Workload, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWorkload not implemented")
}
func (UnimplementedXASControlPlaneServer) GetControlMetrics(context.Context, *GetControlMetricsRequest) (*ControlMetrics, error) {
	return nil, status.Error(codes.Unimplemented, "method GetControlMetrics not implemented")
}
func (UnimplementedXASControlPlaneServer) UpdateRecommenderState(context.Context, *UpdateRecommenderStateRequest) (*RecommenderState, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRecommenderState not implemented")
}
func (UnimplementedXASControlPlaneServer) GetRecommendation(context.Context, *GetRecommendationRequest) (*GetRecommendationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecommendation not implemented")
}
func (UnimplementedXASControlPlaneServer) IngestMetrics(context.Context, *IngestMetricsRequest) (*IngestMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestMetrics not implemented")
}
func (UnimplementedXASControlPlaneServer) mustEmbedUnimplementedXASControlPlaneServer() {}
func (UnimplementedXASControlPlaneServer) testEmbeddedByValue()                         {}

// UnsafeXASControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XASControlPlaneServer will
// result in compilation errors.
type UnsafeXASControlPlaneServer interface {
	mustEmbedUnimplementedXASControlPlaneServer()
}

func RegisterXASControlPlaneServer(s grpc.ServiceRegistrar, srv XASControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedXASControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&XASControlPlane_ServiceDesc, srv)
}

func _XASControlPlane_UpdatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XASControlPlaneServer).UpdatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XASControlPlane_UpdatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XASControlPlaneServer).UpdatePolicy(ctx, req.(*UpdatePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XASControlPlane_DeletePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XASControlPlaneServer).DeletePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XASControlPlane_DeletePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XASControlPlaneServer).DeletePolicy(ctx, req.(*DeletePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XASControlPlane_ListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XASControlPlaneServer).ListPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XASControlPlane_ListPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XASControlPlaneServer).ListPolicies(ctx, req.(*ListPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XASControlPlane_UpdateWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XASControlPlaneServer).UpdateWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XASControlPlane_UpdateWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XASControlPlaneServer).UpdateWorkload(ctx, req.(*UpdateWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XASControlPlane_GetControlMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetControlMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XASControlPlaneServer).GetControlMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XASControlPlane_GetControlMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XASControlPlaneServer).GetControlMetrics(ctx, req.(*GetControlMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XASControlPlane_UpdateRecommenderState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecommenderStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XASControlPlaneServer).UpdateRecommenderState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XASControlPlane_UpdateRecommenderState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XASControlPlaneServer).UpdateRecommenderState(ctx, req.(*UpdateRecommenderStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XASControlPlane_GetRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XASControlPlaneServer).GetRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XASControlPlane_GetRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XASControlPlaneServer).GetRecommendation(ctx, req.(*GetRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XASControlPlane_IngestMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XASControlPlaneServer).IngestMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XASControlPlane_IngestMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XASControlPlaneServer).IngestMetrics(ctx, req.(*IngestMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XASControlPlane_ServiceDesc is the grpc.ServiceDesc for XASControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XASControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xas.v1alpha.XASControlPlane",
	HandlerType: (*XASControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatePolicy",
			Handler:    _XASControlPlane_UpdatePolicy_Handler,
		},
		{
			MethodName: "DeletePolicy",
			Handler:    _XASControlPlane_DeletePolicy_Handler,
		},
		{
			MethodName: "ListPolicies",
			Handler:    _XASControlPlane_ListPolicies_Handler,
		},
		{
			MethodName: "UpdateWorkload",
			Handler:    _XASControlPlane_UpdateWorkload_Handler,
		},
		{
			MethodName: "GetControlMetrics",
			Handler:    _XASControlPlane_GetControlMetrics_Handler,
		},
		{
			MethodName: "UpdateRecommenderState",
			Handler:    _XASControlPlane_UpdateRecommenderState_Handler,
		},
		{
			MethodName: "GetRecommendation",
			Handler:    _XASControlPlane_GetRecommendation_Handler,
		},
		{
			MethodName: "IngestMetrics",
			Handler:    _XASControlPlane_IngestMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xas.proto",
}
